### ISSUE TITLE
include data on testing

### ISSUE THREAD

**Issue by aezarebski** [midas-network/COVID-19#112]
There is a collection of sources for data on testing at the following page:

https://ourworldindata.org/coronavirus-testing-source-data

if this sort of data could be included that would be useful to understand the observation process.

**Comment by wgvanpanhuis** [comment]
Excellent idea! We'll include it as data resource in the listing on the [MIDAS COVID-19 page](https://midasnetwork.us/covid-19/) and will add the standardized metadata to the data collections in this repository.
