### ISSUE TITLE
Weird value of "death" variable in data/cases/global/

### ISSUE THREAD

**Issue by lihualei71** [midas-network/COVID-19#123]
I noticed some weird values of the "death" variable in the line listing data. For example, the 27th case in Japan died at 02/13 but the death variable is 1 in the file 2020_02_18_1800EST_linelist_NIHFogarty.csv and 2020_02_19_1800EST_linelist_NIHFogarty.csv but becomes 1581552000 in all the following files starting from 2/20 to 3/16. There are 50-ish cases with similar issues though with different strange numbers. But interestingly for each case the weird number is consistent based on my partial observation. 

Is this weird number indicating a death? My guess is that this input is recorded as the death date but then transformed into an integer accidentally.

**Comment by LucieContamin** [comment]
Hi @lihualei71 , Thank you for noticing this issue. It is a problem of date format. 
We will fix it and update the files from 2020-02-20 until 2020-03-16 with the correct date format. 
Thanks,
Lucie

**Comment by lihualei71** [comment]
Hi Lucie, thank you for your prompt response! I appreciate all your efforts in putting these datasets together. 

Lihua

**Comment by LucieContamin** [comment]
Hi @lihualei71 , the issue has been resolved in the pull-request #128 .
Many thanks,
Lucie
