### ISSUE TITLE
format change for Ontario Situation Updates breaks csv

### ISSUE THREAD

**Issue by mylesmharrison** [midas-network/COVID-19#142]
As of 2020/03/25 17:30 commas are being used in the status table on the Ontario Ministry of Health's page which is breaking the CSV format (_e.g_ [Cases_in_Ontario_2020-03-26.csv](https://github.com/midas-network/COVID-19/blob/master/data/cases/canada/ontario_situation_updates/Cases_in_Ontario_2020-03-26.csv))

String quoting of CSV fields could be added to address this

**Comment by LucieContamin** [comment]
Hi @mylesmharrison, thank you for the issue. 
It has been resolved in the pull-request #144.
Thanks,
