### ISSUE TITLE
A couple papers with parameter estimates for "time from symptom onset to hospitalization"

### ISSUE THREAD

**Issue by favero-nate** [midas-network/COVID-19#254]
The following papers contain parameter estimates for days from symptom onset to hospitalization that could be added to the dataset here:
* https://www.medrxiv.org/content/10.1101/2020.05.18.20103390v1
* https://www.cdc.gov/mmwr/volumes/69/wr/mm6915e3.htm

I'm new to GitHub, so apologies in advance if this is not the right channel or format to raise this.

**Comment by jessicasalerno** [comment]
Thank you for bringing these to our attention - we will make sure to review them!
