### ISSUE TITLE
20200927 Data is the Same as 20200926 Data

### ISSUE THREAD

**Issue by JosephKarpinski** [midas-network/COVID-19#353]
20200927 Data is the Same as 20200926 Data.
Both 9/26 and 9/27 have the exactly same data, ending at 9/25/20. 
9/27 is missing new data for 9/26/20.
Please review.

<img width="810" alt="Day_D0926" src="https://user-images.githubusercontent.com/37123616/94458539-1126d300-0184-11eb-839a-595235627bf3.png">
<img width="810" alt="Day_D0927" src="https://user-images.githubusercontent.com/37123616/94458544-12580000-0184-11eb-8dcd-04919482db35.png">

**Comment by LucieContamin** [comment]
Hi @JosephKarpinski , Thank you for noticing this issue. The data are copied daily from the GitHub. However it seems that the 2020-09-27 update was done after the time we copy it. We will update the file from 2020-09-27 with 2020-09-26 data.
Thanks,
Lucie

**Comment by LucieContamin** [comment]
The issue has been resolved in the pull-request #362 .
Many thanks,
Lucie
