### ISSUE TITLE
some updates on NSSAC dashboards

### ISSUE THREAD

**Issue by dawenx** [midas-network/COVID-19#39]
On https://github.com/midas-network/COVID-19/blob/master/software_tools/software_catalog.csv
can you help change _creator_contact_ for both of NSSAC dashboards to _nssac_ncov_support@virginia.edu_?

If you don't mind, please update the version for [our surveillance dashboard](http://ncov.bii.virginia.edu/dashboard/) to 0.8.6.

**Comment by LucieContamin** [comment]
Hello @dawenx ,
Thank you for your review.
We update the 'software_catalog.csv' to change the `creator_contact` and update the version of the surveillance dashboard accordingly, the change was made in the pull-request #42 .
