### ISSUE TITLE
a small suggestion

### ISSUE THREAD

**Issue by dawenx** [midas-network/COVID-19#44]
On https://github.com/midas-network/COVID-19/blob/master/software_tools/software_catalog.csv,
maybe column "URL_original" should be moved to be the 3rd column. Just my 2-cent. Feel free to close it without any change.

**Comment by LucieContamin** [comment]
Hi @dawenx , 
Thank you for the idea, we update the `software_catalog.csv` file and the guide associated in the pull-request #47 .
Thanks,
