### ISSUE TITLE
incubation period estimates need metadata about what the "value" is

### ISSUE THREAD

**Issue by nickreich** [midas-network/COVID-19#5]
As it is, it's not clear whether the value for any of the estimates (but I was looking in particular at the incubation period) are means or medians of distributions or exactly what the value represents.

**Comment by LucieContamin** [comment]
Hello @nickreich, 
Thank you for your review.  
We update the `estimates.csv` and `parameter_estimates_data_guide .csv` files to add a variable `value_type` to indicate the type of central statistic represented by the estimate value.
Hope it reply to your question.
