### ISSUE TITLE
Estimates: Cumulative case counts

### ISSUE THREAD

**Issue by srinivvenkat** [midas-network/COVID-19#60]
The first numbers in the estimates readme.md is 'Cumulative case counts'. My understanding is these are total infections (including undetected ones). 

Firstly, these have an 'expiration date', and date when the estimate was done. Also what is being estimated varies widely across the papers. So would be better to have something like 'reporting rate' or 'detection rate', which has better utility for model-builders.

**Comment by wgvanpanhuis** [comment]
Hi Srini, the meaning of "case" in Cumulative case counts may be different in different papers, and work in progress to add definitions to the terms. The dates of estimation and the time interval to which they apply are listed in the information. Reporting rate or detection rate would be useful indeed, and I think is included on the [parameter list file ](https://github.com/midas-network/COVID-19/blob/master/information_for_contributors/parameter_list_v1.1_19Feb2020.csv) that is compiled by US CDC and others as master list of parameters of interest. We can add reporting rate if not already there.
