### ISSUE TITLE
Source of parameters and citations

### ISSUE THREAD

**Issue by srinivvenkat** [midas-network/COVID-19#61]
General question:

Are these parameters being sourced on a pull request basis or is someone actively reading through the literature to get the estimates?

Because over the past few days, I've seen a few China CDC reports which are very comprehensive. It would be useful to include them if they're not already there. For some of these estimates, having an 'N' (number of patients) will be useful and somewhat essential when we try to use the most reliable one.

Finally, I am more comfortable with seeing 'XYZ et al.' as a way of citing them rather than the University (since a lot of the research is collaborative).

**Comment by jessicasalerno** [comment]
Hi Srini,

We have had a few pull requests, but for the most part this is done through literature review. Anyone in the community is welcome to add through pull requests, though, so if you see something we are missing, you are also welcome to add it! 

Thank you for the feedback about the sources. This is how it is listed in the csv, but not the readme. We will discuss making this change.

Best,

Jess

**Comment by wgvanpanhuis** [comment]
Hi Srini, Thanks for your feedback. We will add the N where possible and will change the citation style in the readme to something else, not sure yet exactly what, but working on a better way.
