### ISSUE TITLE
Question: oxford & fogerty line listings

### ISSUE THREAD

**Issue by lwhite1** [midas-network/COVID-19#75]
1) The Oxford set has the most line listings but is not current. Is there another source where a newer version can be found, or is it no longer being maintained?
2) The NIH Fogerty line listings contains 1400 rows. Is there an explanation somewhere of what this subset of cases consists of?

Thank you very much

**Comment by wgvanpanhuis** [comment]
Hi Larry, we have stopped taking snapshots of the Google Sheet-based line listings by the Oxford (and others) group. The same information is available through a Github-based archive, see [here ](https://github.com/beoutbreakprepared/nCoV2019)for the archive and [here ](https://github.com/midas-network/COVID-19/tree/master/data/cases/global/line_listings_oxford_github)for the metadata in our repository about this resource. I hope that helps.
