### ISSUE TITLE
Mention to of historic influenza ?

### ISSUE THREAD

**Issue by hugolpz** [midas-network/COVID-19#77]
![en wikipedia org_wiki_Template_Notable_flu_pandemics](https://user-images.githubusercontent.com/1420189/75828951-4bc2bb80-5dad-11ea-9c3b-74c26929a661.png)

Source : https://en.wikipedia.org/wiki/Template:Notable_flu_pandemics

For R0 : https://en.wikipedia.org/wiki/Template:Notable_flu_pandemics#cite_note-4 
* Biggerstaff, Matthew; Cauchemez, Simon; Reed, Carrie; Gambhir, Manoj; Finelli, Lyn (2014-09-04). "Estimates of the reproduction number for seasonal, pandemic, and zoonotic influenza: a systematic review of the literature". BMC Infectious Diseases. 14 (1): 480. doi:10.1186/1471-2334-14-480. ISSN 1471-2334. PMC 4169819. PMID 25186370.

See also [your section](https://github.com/midas-network/COVID-19#parameter-estimates-for-seasonal-influenza).

**Comment by wgvanpanhuis** [comment]
Thanks for the information! If you are interested to add these parameters to the repository, please enter the information in a CSV file compatible with the [data guide](https://github.com/midas-network/COVID-19/blob/master/information_for_contributors/parameter_estimates_data_guide_v1.1_18Feb2020.csv) and[ CSV template used for Coronavirus](https://github.com/midas-network/COVID-19/blob/master/parameter_estimates/2019_novel_coronavirus/estimates.csv).  Then send the CSV to us or add by pull request. We are happy to add it as well, but after we catch up on COVID-19 estimates.
