### ISSUE TITLE
Activity status ?

### ISSUE THREAD

**Issue by hugolpz** [midas-network/COVID-19#81]
Most of the content of [parameter_estimates/2019_novel_coronavirus](https://github.com/midas-network/COVID-19/tree/master/parameter_estimates/2019_novel_coronavirus) is from 2020-02-1X, mid february. Did you move the effort elsewhere ? @LucieContamin

**Comment by wgvanpanhuis** [comment]
Hi Hugo, thanks for getting in touch! Based on community feedback, parameter estimate information is now being reviewed by the authors before we post them, which is causing a delay in them appearing on the repository. Please bear with us as we work through this process to improve the quality of the information. Updates should be posted towards the end of next week.
